// ── Operator prefix → { operator, circle }
export const PREFIX_DB = {
    // AIRTEL
    "9810": { op: "Airtel", circle: "Delhi" }, "9811": { op: "Airtel", circle: "Delhi" },
    "9868": { op: "Airtel", circle: "Delhi" }, "9871": { op: "Airtel", circle: "Delhi" },
    "9958": { op: "Airtel", circle: "Delhi" }, "9999": { op: "Airtel", circle: "Delhi" },
    "9820": { op: "Airtel", circle: "Mumbai" }, "9821": { op: "Airtel", circle: "Mumbai" },
    "9769": { op: "Airtel", circle: "Mumbai" }, "9987": { op: "Airtel", circle: "Mumbai" },
    "9412": { op: "Airtel", circle: "UP West" }, "9458": { op: "Airtel", circle: "UP East" },
    "9415": { op: "Airtel", circle: "UP East" }, "9936": { op: "Airtel", circle: "UP East" },
    "9839": { op: "Airtel", circle: "UP East" }, "9335": { op: "Airtel", circle: "UP East" },
    "9934": { op: "Airtel", circle: "Bihar" }, "9304": { op: "Airtel", circle: "Bihar" },
    "9693": { op: "Airtel", circle: "Bihar" }, "9771": { op: "Airtel", circle: "Bihar" },
    "9316": { op: "Airtel", circle: "Rajasthan" }, "9414": { op: "Airtel", circle: "Rajasthan" },
    "9828": { op: "Airtel", circle: "Rajasthan" }, "9829": { op: "Airtel", circle: "Rajasthan" },
    "9560": { op: "Airtel", circle: "Delhi" }, "9599": { op: "Airtel", circle: "Delhi" },
    "9711": { op: "Airtel", circle: "Delhi" }, "9718": { op: "Airtel", circle: "Delhi" },
    "8527": { op: "Airtel", circle: "Delhi" }, "8800": { op: "Airtel", circle: "Delhi" },
    "7011": { op: "Airtel", circle: "Delhi" }, "7982": { op: "Airtel", circle: "Delhi" },
    "9205": { op: "Airtel", circle: "Haryana" }, "9896": { op: "Airtel", circle: "Haryana" },
    "9416": { op: "Airtel", circle: "Haryana" }, "9466": { op: "Airtel", circle: "Haryana" },
    "9419": { op: "Airtel", circle: "J&K" }, "9797": { op: "Airtel", circle: "J&K" },
    "9906": { op: "Airtel", circle: "J&K" }, "9419": { op: "Airtel", circle: "J&K" },
    "9431": { op: "Airtel", circle: "Jharkhand" }, "8986": { op: "Airtel", circle: "Jharkhand" },
    "9471": { op: "Airtel", circle: "Jharkhand" }, "8340": { op: "Airtel", circle: "Bihar" },
    "9480": { op: "Airtel", circle: "Karnataka" }, "9481": { op: "Airtel", circle: "Karnataka" },
    "9900": { op: "Airtel", circle: "Karnataka" }, "9901": { op: "Airtel", circle: "Karnataka" },
    "9846": { op: "Airtel", circle: "Kerala" }, "9847": { op: "Airtel", circle: "Kerala" },
    "9605": { op: "Airtel", circle: "Kerala" }, "9526": { op: "Airtel", circle: "Kerala" },
    "9827": { op: "Airtel", circle: "MP" }, "9893": { op: "Airtel", circle: "MP" },
    "9753": { op: "Airtel", circle: "MP" }, "9826": { op: "Airtel", circle: "MP" },
    "9373": { op: "Airtel", circle: "Maharashtra" }, "9823": { op: "Airtel", circle: "Maharashtra" },
    "9860": { op: "Airtel", circle: "Maharashtra" }, "9561": { op: "Airtel", circle: "Maharashtra" },
    "9433": { op: "Airtel", circle: "West Bengal" }, "9434": { op: "Airtel", circle: "West Bengal" },
    "9832": { op: "Airtel", circle: "West Bengal" }, "7595": { op: "Airtel", circle: "West Bengal" },
    "9444": { op: "Airtel", circle: "Tamil Nadu" }, "9445": { op: "Airtel", circle: "Tamil Nadu" },
    "9841": { op: "Airtel", circle: "Tamil Nadu" }, "9791": { op: "Airtel", circle: "Tamil Nadu" },
    "9177": { op: "Airtel", circle: "Andhra Pradesh" }, "9849": { op: "Airtel", circle: "Andhra Pradesh" },
    "9866": { op: "Airtel", circle: "Andhra Pradesh" }, "9963": { op: "Airtel", circle: "Andhra Pradesh" },
    // JIO
    "6260": { op: "Jio", circle: "MP" }, "6261": { op: "Jio", circle: "MP" },
    "7000": { op: "Jio", circle: "MP" }, "7001": { op: "Jio", circle: "UP East" },
    "7002": { op: "Jio", circle: "Rajasthan" }, "7003": { op: "Jio", circle: "Delhi" },
    "7004": { op: "Jio", circle: "Gujarat" }, "7005": { op: "Jio", circle: "Maharashtra" },
    "7006": { op: "Jio", circle: "UP West" }, "7007": { op: "Jio", circle: "Bihar" },
    "7008": { op: "Jio", circle: "Odisha" }, "7009": { op: "Jio", circle: "Haryana" },
    "7568": { op: "Jio", circle: "Rajasthan" }, "8269": { op: "Jio", circle: "MP" },
    "8349": { op: "Jio", circle: "MP" }, "9109": { op: "Jio", circle: "MP" },
    "6261": { op: "Jio", circle: "MP" }, "6262": { op: "Jio", circle: "MP" },
    "6263": { op: "Jio", circle: "UP East" }, "6264": { op: "Jio", circle: "Bihar" },
    "6265": { op: "Jio", circle: "Bihar" }, "6266": { op: "Jio", circle: "UP West" },
    "6267": { op: "Jio", circle: "Maharashtra" }, "6268": { op: "Jio", circle: "Gujarat" },
    "6269": { op: "Jio", circle: "Rajasthan" }, "9175": { op: "Jio", circle: "Maharashtra" },
    "9326": { op: "Jio", circle: "Maharashtra" }, "9619": { op: "Jio", circle: "Maharashtra" },
    "7350": { op: "Jio", circle: "UP East" }, "7838": { op: "Jio", circle: "Delhi" },
    "8299": { op: "Jio", circle: "UP East" }, "8874": { op: "Jio", circle: "UP East" },
    "9076": { op: "Jio", circle: "Maharashtra" }, "9307": { op: "Jio", circle: "Bihar" },
    "9508": { op: "Jio", circle: "Bihar" }, "9155": { op: "Jio", circle: "Andhra Pradesh" },
    "9059": { op: "Jio", circle: "Andhra Pradesh" }, "9010": { op: "Jio", circle: "Andhra Pradesh" },
    "9182": { op: "Jio", circle: "Andhra Pradesh" }, "9247": { op: "Jio", circle: "Andhra Pradesh" },
    // Vi (Vodafone Idea)
    "9320": { op: "Vi", circle: "Mumbai" }, "9321": { op: "Vi", circle: "Mumbai" },
    "9322": { op: "Vi", circle: "Mumbai" }, "9323": { op: "Vi", circle: "Mumbai" },
    "9324": { op: "Vi", circle: "Mumbai" }, "9325": { op: "Vi", circle: "Mumbai" },
    "9768": { op: "Vi", circle: "Delhi" }, "9773": { op: "Vi", circle: "Delhi" },
    "9990": { op: "Vi", circle: "Delhi" }, "9311": { op: "Vi", circle: "Delhi" },
    "9312": { op: "Vi", circle: "Delhi" }, "9313": { op: "Vi", circle: "Delhi" },
    "9773": { op: "Vi", circle: "Delhi" }, "9899": { op: "Vi", circle: "Delhi" },
    "9829": { op: "Vi", circle: "Rajasthan" }, "9460": { op: "Vi", circle: "Rajasthan" },
    "9461": { op: "Vi", circle: "Rajasthan" }, "9462": { op: "Vi", circle: "Rajasthan" },
    "9425": { op: "Vi", circle: "MP" }, "9926": { op: "Vi", circle: "MP" },
    "9827": { op: "Vi", circle: "MP" }, "9977": { op: "Vi", circle: "MP" },
    "9924": { op: "Vi", circle: "Gujarat" }, "9925": { op: "Vi", circle: "Gujarat" },
    "9978": { op: "Vi", circle: "Gujarat" }, "8980": { op: "Vi", circle: "Gujarat" },
    "9391": { op: "Vi", circle: "Andhra Pradesh" }, "9440": { op: "Vi", circle: "Andhra Pradesh" },
    "9441": { op: "Vi", circle: "Andhra Pradesh" }, "9948": { op: "Vi", circle: "Andhra Pradesh" },
    // BSNL
    "9411": { op: "BSNL", circle: "UP West" }, "9412": { op: "BSNL", circle: "UP West" },
    "9413": { op: "BSNL", circle: "Rajasthan" }, "9418": { op: "BSNL", circle: "HP" },
    "9419": { op: "BSNL", circle: "J&K" }, "9422": { op: "BSNL", circle: "Maharashtra" },
    "9423": { op: "BSNL", circle: "Maharashtra" }, "9450": { op: "BSNL", circle: "UP East" },
    "9451": { op: "BSNL", circle: "UP East" }, "9452": { op: "BSNL", circle: "UP East" },
    "9453": { op: "BSNL", circle: "UP East" }, "9454": { op: "BSNL", circle: "UP East" },
    "9455": { op: "BSNL", circle: "UP East" },
};

// ── Plans database per operator (Real plans as of 2025-26)
export const OPERATOR_PLANS = {
    Airtel: [
        // Data Add-ons
        { id: 1, amount: 19, data: "200 MB", validity: "1 Day", calls: "—", sms: "—", type: "Data", popular: false, desc: "Emergency data pack" },
        { id: 2, amount: 49, data: "1 GB", validity: "28 Days", calls: "—", sms: "—", type: "Data", popular: false, desc: "Data add-on booster" },
        { id: 3, amount: 99, data: "2 GB", validity: "28 Days", calls: "—", sms: "—", type: "Data", popular: false, desc: "Data top-up" },
        // Smart Recharge
        { id: 4, amount: 155, data: "1 GB/Day", validity: "20 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Budget plan" },
        { id: 5, amount: 179, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Value recharge" },
        { id: 6, amount: 199, data: "1.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Most popular — 42 GB total" },
        { id: 7, amount: 249, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "High data plan" },
        { id: 8, amount: 265, data: "1.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "With Disney+ Hotstar Mobile" },
        { id: 9, amount: 299, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Best value — 56 GB total" },
        { id: 10, amount: 359, data: "2.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Heavy user — 70 GB total" },
        { id: 11, amount: 379, data: "2.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "With Wynk Music" },
        { id: 12, amount: 399, data: "2 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "2 months — 112 GB total" },
        { id: 13, amount: 449, data: "2.5 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2 months premium" },
        { id: 14, amount: 479, data: "3 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2 months heavy data" },
        { id: 15, amount: 549, data: "2 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months value" },
        { id: 16, amount: 599, data: "3 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months — 252 GB total" },
        { id: 17, amount: 699, data: "2.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months with OTT" },
        { id: 18, amount: 719, data: "2.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months with Disney+ Hotstar" },
        { id: 19, amount: 839, data: "2 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months premium OTT bundle" },
        { id: 20, amount: 999, data: "3 GB/Day", validity: "90 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Quarterly plan — 270 GB" },
        // Annual
        { id: 21, amount: 1799, data: "2.5 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual plan — 912 GB" },
        { id: 22, amount: 2449, data: "3 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual premium" },
        { id: 23, amount: 2999, data: "3 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: true, desc: "Best annual — 1095 GB + Disney+" },
        { id: 24, amount: 3599, data: "3 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual elite — 1095 GB + Full OTT" },
    ],

    Jio: [
        // Daily / Weekly
        { id: 1, amount: 15, data: "1 GB", validity: "1 Day", calls: "Unlimited", sms: "—", type: "Daily", popular: false, desc: "Emergency daily recharge" },
        { id: 2, amount: 19, data: "2 GB", validity: "1 Day", calls: "Unlimited", sms: "—", type: "Daily", popular: false, desc: "Power daily plan" },
        { id: 3, amount: 29, data: "1 GB/Day", validity: "7 Days", calls: "Unlimited", sms: "50/D", type: "Weekly", popular: false, desc: "Weekly plan — 7 GB total" },
        { id: 4, amount: 39, data: "6 GB", validity: "7 Days", calls: "Unlimited", sms: "50/D", type: "Weekly", popular: false, desc: "Weekly value — JioCinema" },
        { id: 5, amount: 49, data: "2 GB", validity: "14 Days", calls: "Unlimited", sms: "50/D", type: "Weekly", popular: false, desc: "Fortnightly starter" },
        { id: 6, amount: 89, data: "12 GB", validity: "14 Days", calls: "Unlimited", sms: "50/D", type: "Weekly", popular: false, desc: "Fortnightly — JioCinema" },
        // Monthly Plans
        { id: 7, amount: 119, data: "12 GB", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Budget monthly — JioCinema Basic" },
        { id: 8, amount: 149, data: "1.5 GB/Day", validity: "24 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Smart 24-day plan — 36 GB" },
        { id: 9, amount: 159, data: "1 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "28 GB monthly" },
        { id: 10, amount: 189, data: "1.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "42 GB monthly — JioCinema" },
        { id: 11, amount: 209, data: "1.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Most popular — 42 GB + JioCinema Prem" },
        { id: 12, amount: 239, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "56 GB monthly" },
        { id: 13, amount: 249, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "56 GB + JioCinema Premium" },
        { id: 14, amount: 299, data: "3 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Best seller — 84 GB + JioCinema Prem" },
        { id: 15, amount: 349, data: "3 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "84 GB + JioCloud 100 GB" },
        { id: 16, amount: 399, data: "2.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "70 GB + Full OTT Pack" },
        // 2-Month Plans
        { id: 17, amount: 395, data: "1.5 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2 months — 84 GB" },
        { id: 18, amount: 449, data: "2 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2 months — 112 GB" },
        { id: 19, amount: 479, data: "2.5 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "2 months best — 140 GB + JioCinema" },
        { id: 20, amount: 555, data: "3 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2 months — 168 GB" },
        // 3-Month Plans
        { id: 21, amount: 533, data: "1.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months — 126 GB" },
        { id: 22, amount: 601, data: "2 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months — 168 GB" },
        { id: 23, amount: 666, data: "2.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months — 210 GB + JioCinema" },
        { id: 24, amount: 719, data: "3 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months — 252 GB" },
        { id: 25, amount: 799, data: "2 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months + Full OTT" },
        { id: 26, amount: 899, data: "3 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months premium OTT" },
        { id: 27, amount: 999, data: "3 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Quarterly — JioCloud + OTT" },
        // Annual Plans
        { id: 28, amount: 1559, data: "1.5 GB/Day", validity: "336 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual value — JioCinema Basic" },
        { id: 29, amount: 1899, data: "2 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual — 730 GB" },
        { id: 30, amount: 2399, data: "2 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual — 730 GB + JioCinema Prem" },
        { id: 31, amount: 2799, data: "2.5 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual — 912 GB + JioCinema Prem" },
        { id: 32, amount: 2999, data: "3 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: true, desc: "Best annual — 1095 GB + Full OTT" },
        { id: 33, amount: 3599, data: "3 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual elite — 1095 GB + JioCloud 100GB" },
        // 5G Specific
        { id: 34, amount: 349, data: "Unlimited 5G", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "True 5G unlimited — JioAirFiber zones" },
        { id: 35, amount: 601, data: "Unlimited 5G", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "5G 2 months unlimited" },
        { id: 36, amount: 899, data: "Unlimited 5G", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: true, desc: "5G 3 months — best 5G plan" },
    ],

    Vi: [
        // Short / Add-on
        { id: 1, amount: 19, data: "200 MB", validity: "2 Days", calls: "—", sms: "—", type: "Data", popular: false, desc: "Data emergency booster" },
        { id: 2, amount: 49, data: "1 GB", validity: "28 Days", calls: "—", sms: "—", type: "Data", popular: false, desc: "Data add-on" },
        { id: 3, amount: 79, data: "6 GB", validity: "14 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Fortnightly plan" },
        { id: 4, amount: 129, data: "2 GB/Day", validity: "20 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "20-day plan" },
        // Monthly
        { id: 5, amount: 155, data: "1 GB/Day", validity: "24 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Budget 24-day plan" },
        { id: 6, amount: 199, data: "1.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Most popular — 42 GB" },
        { id: 7, amount: 209, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "56 GB monthly" },
        { id: 8, amount: 249, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "56 GB + Vi Movies & TV" },
        { id: 9, amount: 299, data: "2.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Best Vi — 70 GB + Weekend Rollover" },
        { id: 10, amount: 299, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Hero Unlimited — Weekend Rollover" },
        { id: 11, amount: 399, data: "3 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "84 GB + Data Rollover" },
        // 2-Month
        { id: 12, amount: 365, data: "1.5 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2 months — 84 GB" },
        { id: 13, amount: 447, data: "2 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2 months — 112 GB" },
        { id: 14, amount: 479, data: "2.5 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2 months — 140 GB + Rollover" },
        // 3-Month
        { id: 15, amount: 495, data: "1.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months — 126 GB" },
        { id: 16, amount: 555, data: "2 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months — 168 GB" },
        { id: 17, amount: 601, data: "2.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months — 210 GB" },
        { id: 18, amount: 719, data: "3 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months — 252 GB + OTT" },
        { id: 19, amount: 839, data: "2 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "3 months + Vi Movies & TV" },
        { id: 20, amount: 999, data: "2.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Quarterly plan" },
        // Annual
        { id: 21, amount: 1799, data: "1.5 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual — 547 GB" },
        { id: 22, amount: 2399, data: "2 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: true, desc: "Annual best — 730 GB + Vi Movies & TV" },
        { id: 23, amount: 2999, data: "2.5 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual premium — 912 GB" },
    ],

    BSNL: [
        // Short Term
        { id: 1, amount: 22, data: "1 GB", validity: "18 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Ultra budget starter" },
        { id: 2, amount: 25, data: "2 GB", validity: "2 Days", calls: "Unlimited", sms: "—", type: "Daily", popular: false, desc: "Weekend plan" },
        { id: 3, amount: 56, data: "1 GB/Day", validity: "7 Days", calls: "Unlimited", sms: "100/D", type: "Weekly", popular: false, desc: "Weekly plan — 7 GB" },
        { id: 4, amount: 94, data: "2 GB/Day", validity: "20 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "20-day val plan" },
        // Monthly
        { id: 5, amount: 107, data: "2 GB/Day", validity: "22 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "22-day plan" },
        { id: 6, amount: 118, data: "1 GB/Day", validity: "26 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "26-day plan — 26 GB" },
        { id: 7, amount: 148, data: "2 GB/Day", validity: "26 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "26 days — 52 GB" },
        { id: 8, amount: 197, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Best BSNL — 56 GB + Disney+ Hotstar" },
        { id: 9, amount: 237, data: "3 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "84 GB monthly" },
        { id: 10, amount: 247, data: "2 GB/Day", validity: "30 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "30 days — 60 GB" },
        // 3-Month
        { id: 11, amount: 397, data: "3 GB/Day", validity: "80 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "80 days — 240 GB" },
        { id: 12, amount: 485, data: "2 GB/Day", validity: "90 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Quarterly — 180 GB" },
        { id: 13, amount: 599, data: "2 GB/Day", validity: "120 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "4 months — 240 GB" },
        // Long Term
        { id: 14, amount: 797, data: "3 GB/Day", validity: "160 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "5 months — 480 GB" },
        { id: 15, amount: 1198, data: "3 GB/Day", validity: "240 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "8 months plan" },
        // Annual
        { id: 16, amount: 1515, data: "2 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual — 730 GB" },
        { id: 17, amount: 2399, data: "3 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: true, desc: "Annual best — 1095 GB + Disney+" },
    ],
};


// ── DTH Providers & Plans
export const DTH_PROVIDERS = {
    "Tata Play": {
        logo: "🔵",
        color: "#003087",
        plans: [
            { id: 1, amount: 199, name: "Basic SD", channels: "210+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 299, name: "Basic HD", channels: "220+", validity: "30 Days", type: "HD" },
            { id: 3, amount: 399, name: "Family HD", channels: "290+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 499, name: "Super HD", channels: "350+", validity: "30 Days", type: "HD" },
            { id: 5, amount: 699, name: "Premium 4K", channels: "400+", validity: "30 Days", type: "4K" },
        ]
    },
    "Airtel Xstream": {
        logo: "🔴",
        color: "#E40000",
        plans: [
            { id: 1, amount: 249, name: "Base SD", channels: "200+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 349, name: "HD Basic", channels: "250+", validity: "30 Days", type: "HD" },
            { id: 3, amount: 499, name: "HD Family", channels: "320+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 599, name: "HD Premium", channels: "400+", validity: "30 Days", type: "HD" },
            { id: 5, amount: 799, name: "Elite 4K", channels: "450+", validity: "30 Days", type: "4K" },
        ]
    },
    "Dish TV": {
        logo: "🟠",
        color: "#FF6600",
        plans: [
            { id: 1, amount: 153, name: "Silver SD", channels: "195+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 249, name: "Gold SD", channels: "260+", validity: "30 Days", type: "SD" },
            { id: 3, amount: 349, name: "Diamond HD", channels: "310+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 499, name: "Platinum HD", channels: "380+", validity: "30 Days", type: "HD" },
        ]
    },
    "Sun Direct": {
        logo: "🟡",
        color: "#FFA500",
        plans: [
            { id: 1, amount: 149, name: "Silver", channels: "125+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 249, name: "Gold", channels: "205+", validity: "30 Days", type: "SD" },
            { id: 3, amount: 349, name: "Diamond HD", channels: "240+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 499, name: "Platinum", channels: "300+", validity: "30 Days", type: "HD" },
        ]
    },
    "Videocon D2H": {
        logo: "🔷",
        color: "#0066CC",
        plans: [
            { id: 1, amount: 125, name: "Lite SD", channels: "155+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 249, name: "Smart HD", channels: "230+", validity: "30 Days", type: "HD" },
            { id: 3, amount: 399, name: "Super HD", channels: "290+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 549, name: "Ultra HD", channels: "350+", validity: "30 Days", type: "HD" },
        ]
    },
};

// ── BBPS Bill Categories & All India Billers
export const BILL_CATEGORIES = [
    {
        id: "electricity", label: "Electricity", icon: "⚡", color: "#f59e0b",
        billers: [
            { name: "Ajmer Vidyut Vitran Nigam Limited (AVVNL)", opcode: "AVE" },
            { name: "APDCL - ASSAM", opcode: "AAE" },
            { name: "APEPDCL-Eastern Power Distribution CO AP Ltd", opcode: "APE" },
            { name: "APSPDCL-Southern Power Distribution CO AP Ltd", opcode: "ASE" },
            { name: "Bangalore Electricity Supply Company", opcode: "BBE" },
            { name: "Bharatpur Electricity Services Ltd. (BESL)", opcode: "BEE" },
            { name: "Bikaner Electricity Supply Limited (BKESL)", opcode: "BKE" },
            { name: "Brihan Mumbai Electric Supply and Transport Undertaking", opcode: "BME" },
            { name: "BSES Rajdhani Power Limited", opcode: "BRE" },
            { name: "BSES Yamuna Power Limited", opcode: "BYE" },
            { name: "Calcutta Electricity Supply Ltd (CESC)", opcode: "CWE" },
            { name: "Chamundeshwari Electricity Supply Corp Ltd (CESCOM) - Non-RAPDRP", opcode: "CNE" },
            { name: "Chamundeshwari Electricity Supply Corp Ltd (CESCOM) -RAPDRP", opcode: "CRE" },
            { name: "Chhattisgarh State Electricity Board", opcode: "CCE" },
            { name: "Dakshin Haryana Bijli Vitran Nigam (DHBVN)", opcode: "DHE", subDivLabel: "Mobile Number (10 digits)" },
            { name: "Daman and Diu Electricity", opcode: "DDE" },
            { name: "DNH Power Distribution Company Limited", opcode: "DNE" },
            { name: "Gulbarga Electricity Supply Company Limited (GESCOM)", opcode: "GEE" },
            { name: "Himachal Pradesh State Electricity Board (HPSEB)", opcode: "HPE" },
            { name: "Hubli Electricity Supply Company Ltd (HESCOM) - Non-RAPDRP", opcode: "HNE" },
            { name: "Hubli Electricity Supply Company Ltd (HESCOM) - RAPDRP", opcode: "HRE" },
            { name: "India Power Corporation - West Bengal", opcode: "IWE" },
            { name: "India Power Corporation Limited - Bihar", opcode: "IBE" },
            { name: "Jaipur Vidyut Vitran Nigam (JVVNL)", opcode: "JIE" },
            { name: "Jamshedpur Utilities and Services Company Limited", opcode: "JUE" },
            { name: "Jharkhand Bijli Vitran Nigam Ltd (JBVNL)", opcode: "JBE", subDivLabel: "Subdivision Code (1-3 digits)" },
            { name: "Jodhpur Vidyut Vitran Nigam Limited (JDVVNL)", opcode: "JDE" },
            { name: "Kanpur Electricity Supply Company", opcode: "KNE" },
            { name: "Kota Electricity Distribution Limited (KEDL)", opcode: "KTE" },
            { name: "Madhya Pradesh Madhya Kshetra Vidyut Vitaran Co. Ltd.-Rural (MPMKVVCL)", opcode: "MME" },
            { name: "Madhya Pradesh Madhya Kshetra Vidyut Vitaran Co. Ltd.-Urban", opcode: "MUE" },
            { name: "Madhya Pradesh Paschim Kshetra Vidyut Vitaran - Indore", opcode: "MPE" },
            { name: "Madhya Pradesh Poorv Kshetra Vidyut Vitaran - RURAL (MPPKVVCL)", opcode: "MRE" },
            { name: "Meghalaya Power Dist Corp Ltd", opcode: "MHE" },
            { name: "MSEDC Limited", opcode: "MSE", subDivLabel: "Billing Unit (4 digits)" },
            { name: "Muzaffarpur Vidyut Vitran Limited", opcode: "MZE" },
            { name: "NESCO, Odisha", opcode: "NSE" },
            { name: "Noida Power Company Limited", opcode: "NNE" },
            { name: "North Bihar Power Distribution Company Ltd.", opcode: "NBE" },
            { name: "Punjab State Power Corporation Ltd (PSPCL)", opcode: "PSE" },
            { name: "Reliance Energy", opcode: "REE", subDivLabel: "Cycle Number (2 digits)" },
            { name: "Sikkim Power - RURAL (SKMPWR)", opcode: "SPE" },
            { name: "SNDL Nagpur", opcode: "SDE" },
            { name: "South Bihar Power Distribution Company Ltd.", opcode: "SBE" },
            { name: "SOUTHCO, Odisha", opcode: "STE" },
            { name: "Tamil Nadu Electricity Board (TNEB)", opcode: "TNE" },
            { name: "Tata Power - Mumbai", opcode: "TME" },
            { name: "TATA Power-Delhi", opcode: "NDE" },
            { name: "Telangana Southern Power Distribution Co Ltd", opcode: "TLE" },
            { name: "Torrent Power - Agra", opcode: "TAE", subDivLabel: "City Name (Pass Agra)" },
            { name: "Torrent Power - Ahmedabad", opcode: "THE", subDivLabel: "City Name (Pass Ahmedabad)" },
            { name: "Torrent Power - Bhiwandi", opcode: "TBE" },
            { name: "Torrent Power - Surat", opcode: "TSE", subDivLabel: "City Name (Pass Surat)" },
            { name: "TP Ajmer Distribution Ltd (TPADL)", opcode: "AJE" },
            { name: "Tripura State Electricity Corporation Ltd", opcode: "TTE" },
            { name: "Uttar Haryana Bijli Vitran Nigam (UHBVN)", opcode: "UHE", subDivLabel: "Mobile Number (10 digits)" },
            { name: "Uttar Pradesh Power Corp Ltd (UPPCL) - RURAL", opcode: "URE" },
            { name: "Uttar Pradesh Power Corp Ltd (UPPCL) - URBAN", opcode: "UBE" },
            { name: "Uttarakhand Power Corporation Limited", opcode: "UKE" },
            { name: "WESCO Utility", opcode: "WSE" },
            { name: "West Bengal State Electricity Distribution Co. Ltd (WBSEDCL)", opcode: "WBE" }
        ],
    },
    {
        id: "water", label: "Water", icon: "💧", color: "#3b82f6",
        billers: [
            "Delhi Jal Board (DJB)", "MCGM Mumbai Water", "BWSSB Bangalore",
            "Chennai Metro Water (CMWSSB)", "Hyderabad Metro Water (HMWS&SB)",
            "Pune Municipal Corporation Water", "Kolkata Municipal Corporation Water",
            "Ahmedabad Municipal Corporation Water", "Surat Municipal Corporation Water",
            "Jaipur Nagar Nigam Water", "Lucknow Nagar Nigam Water",
            "Nagpur Municipal Smart Card", "Nashik Municipal Corporation Water",
            "Thane Municipal Corporation Water", "Navi Mumbai Municipal Water",
            "Greater Noida Water", "Noida Authority Water", "Gurgaon MCG Water",
        ],
    },
    {
        id: "gas", label: "Piped Gas", icon: "🔥", color: "#ef4444",
        billers: [
            "Indraprastha Gas (IGL) — Delhi / NCR", "Mahanagar Gas (MGL) — Mumbai",
            "Gujarat Gas Ltd", "Torrent Gas", "Adani Total Gas",
            "GAIL Gas Ltd", "AG&P Pratham (Gujarat)", "Thinks Gas (Rajasthan)",
            "Central UP Gas Ltd (CUGL)", "Green Gas Ltd (Lucknow / Agra)",
            "Maharashtra Natural Gas Ltd (MNGL)", "Sabarmati Gas Ltd",
            "Bhagyanagar Gas Ltd (Hyderabad)", "SITI Energy (Rajkot)",
            "Charotar Gas Sahakari Mandali", "Vadodara Gas Ltd",
        ],
    },
    {
        id: "broadband", label: "Broadband", icon: "🌐", color: "#8b5cf6",
        billers: [
            "Airtel Xstream Fiber", "Jio Fiber", "BSNL Broadband", "VI Home Broadband",
            "ACT Fibernet", "Hathway Broadband", "YOU Broadband", "Excitel Fiber",
            "Tikona Broadband", "Spectra (Den Networks)", "Sify Technologies",
            "RailTel Broadband", "MTNL Delhi Broadband", "MTNL Mumbai Broadband",
            "GTPL Broadband", "Gigatel Fiber", "DEN Networks", "Connect Broadband (Punjab)",
            "Fastway Networks (Punjab)", "MEGHBELA Broadband (West Bengal)",
        ],
    },
    {
        id: "landline", label: "Landline / Postpaid", icon: "📞", color: "#06b6d4",
        billers: [
            "BSNL Landline (All India)", "MTNL Delhi Landline", "MTNL Mumbai Landline",
            "Airtel Landline", "VI Postpaid", "Airtel Postpaid",
            "Jio Postpaid", "BSNL Postpaid Mobile",
            "Tata Teleservices", "Quadrant Televentures (HFCL)",
        ],
    },
    {
        id: "insurance", label: "Insurance", icon: "🛡️", color: "#10b981",
        billers: [
            "LIC of India Premium", "SBI Life Insurance", "HDFC Life Insurance",
            "ICICI Prudential Life", "Bajaj Allianz Life", "Max Life Insurance",
            "Tata AIA Life", "Kotak Mahindra Life", "PNB MetLife", "Aditya Birla Sun Life",
            "Canara HSBC Life", "Future Generali Life", "Reliance Nippon Life",
            "Star Health & Allied Insurance", "HDFC ERGO Health", "ICICI Lombard Health",
            "Niva Bupa Health Insurance", "Care Health Insurance", "Digit Insurance",
            "New India Assurance (Motor/Health)", "United India Insurance",
            "Oriental Insurance", "National Insurance Company",
        ],
    },
    {
        id: "creditcard", label: "Credit Card", icon: "💳", color: "#7c3aed",
        billers: [
            "SBI Card", "HDFC Bank Credit Card", "ICICI Bank Credit Card",
            "Axis Bank Credit Card", "Kotak Mahindra Credit Card", "Yes Bank Credit Card",
            "IndusInd Bank Credit Card", "RBL Bank Credit Card", "AU Small Finance Credit Card",
            "Bank of Baroda Credit Card", "Canara Bank Credit Card", "Union Bank Credit Card",
            "Punjab National Bank Credit Card", "Federal Bank Credit Card",
            "IDFC First Bank Credit Card", "OneCard (FedFina)", "Amazon Pay ICICI Card",
            "Flipkart Axis Bank Card", "Citi Bank Credit Card", "Standard Chartered Card",
            "American Express India",
        ],
    },
    {
        id: "loan", label: "Loan EMI", icon: "🏦", color: "#1d4ed8",
        billers: [
            "SBI Home Loan", "HDFC Home Loan", "LIC Housing Finance",
            "ICICI Home Loan", "Axis Bank Home Loan", "Kotak Mahindra Home Loan",
            "PNB Housing Finance", "Indiabulls Housing Finance",
            "Bajaj Finserv Personal Loan", "Bajaj Finserv Home Loan",
            "Tata Capital Home Loan", "Aditya Birla Finance",
            "Shriram Finance", "Muthoot Finance", "Manappuram Finance",
            "IDBI Bank Home Loan", "Bank of Baroda Home Loan",
            "Canara Bank Home Loan", "Federal Bank Home Loan",
            "HDB Financial Services", "Hero FinCorp", "L&T Finance",
            "Mahindra Finance", "Cholamandalam Investment and Finance",
        ],
    },
];

// ── PAN API Endpoint (backend)
export const PAN_API = "/api/pan/apply";
export const RECHARGE_API = "/api/recharge";
export const BILL_PAY_API = "/api/bill-pay";
export const BILL_FETCH_API = "/api/bill-fetch";

